pipeline {
  # 代理: 告诉 Jenkins 在哪里以及如何执行 step (分配 workspace)
  agent any

  # 环境变量
  environment {
    DISABLE_AUTH = 'true'
    DB_ENGINE    = 'sqlite'
  }

  # 阶段集合
  stages {
    # 单个集合 构建
    stage('Build') {
      steps {
        # 重试
        retry(3) {
          sh 'echo "Hello World"'
        }
        # 超时
        timeout(time: 3, unit: 'MINUTES') {
          sh '''
              echo "Multiline shell steps works too"
              ls -lah
          '''
        }
      }
    }

    # 测试
    stage('Test') {
      steps {
        echo 'Testing'
      }
    }

    # 部署
    stage('Deploy') {
      steps {
        echo 'Deploying'
      }
    }

    # 添加环境变量
    stage('Deploy - Staging') {

    }

    stage('Deploy - Production') {

    }
  }

  # 完成时操作 hooks
  # 记录日志
  # 清理 workspace
  # 发送错误邮件
  post {
    # 总是执行
    always {
      echo 'This will always run'
    }
    # 成功时候执行
    success {
      echo 'This will run only if successful'
    }
    # 失败时候执行
    failure {
      echo 'This will run only if failed'
    }
    unstable {
      echo 'This will run only if the run was marked as unstable'
    }
    # pipeline 状态发生改变
    changed {
      echo 'This will run only if the state of the Pipeline has changed'
      echo 'For example, if the Pipeline was previously failing but is now successful'
    }
  }
}