export enum ActionTypes {
    LOG_OUT = 'LOG_OUT',
    ADD_TODO = 'ADD_TODO',
    TOGGLE_TODO = 'TOGGLE_TODO',
    SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER',
    CHANGE_NAME = 'CHANGE_NAME',
    CHANGE_AGE = 'CHANGE_AGE',
}