version: '3.8'
services:
 mysqlserver:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=jdbc
      - MYSQL_PASSWORD=jdbc
      - MYSQL_DATABASE=jdbc-demo
    volumes:
      - jdbc_mysql_data:/var/lib/mysql
      - jdbc_mysql_config:/etc/mysql/conf.d
volumes:
    jdbc_mysql_data:
    jdbc_mysql_config:
    